dashborad/urls.py
#!/usr/bin/env python
#-*- coding:utf8 -*-
from django.conf.urls import url ,include

from dashborad import  views
from dashborad import  user
from dashborad.user import  group,permission
from dashborad.server import  idc,product
from dashborad import server
from dashborad import zabbix
from dashborad.zabbix import template

urlpatterns = [
    url(r'^user/login/$', views.login_view),
    url(r'^user/logout/$', views.logout_view),
    url(r'^$', views.IndexView.as_view()),
    #url(r'^user/userlist/$',user.UserListView.as_view()),
    url(r'^permission/',include([
        url(r'^none/$',views.permission),
        url(r'^list/$', user.permission.PermissionView.as_view()),
        url(r'^modifycodename/$', user.permission.ModifyPermissionView.as_view()),
    ]
    ) ),
    url(r'^user/',include([
        #url(r'^userlist/$',user.UserListView.as_view()),
        url(r'^userlist/$',user.USERLISTVIEW.as_view()),
        url(r'^modifystatus/$',user.ModifyUserStatusView.as_view()),
        url(r'^modifydepartment/$',user.ModifyDepartmentView.as_view()),
        url(r'^modifyphone/$',user.ModifyPhoneView.as_view()),
        url(r'^profilelist/$',user.ProfilelistView.as_view()),

    ]
    )),
    url(r'^group/',include([
        url(r'^list/$',user.group.GroupView.as_view()),
        url(r'^add/$',user.group.GroupView.as_view()),
        url(r'^usergrouplist/$',user.group.UserGroupView.as_view()),
        url(r'^usergroupadd/$',user.group.UserGroupView.as_view()),
        url(r'^groupuserlist/$',user.group.GroupUserView.as_view()),
        url(r'^groupuserdel/$',user.group.GroupUserView.as_view()),
        url(r'^permission/$',user.group.Groupermission.as_view()),
        url(r'^permissionlist/$',user.group.GroupPermissionlist.as_view()),

    ]
    ) ),
    url(r'^server/', include([
        url(r'^idc/', include([
            url(r'^list/$',idc.ListIdcView.as_view()),
            url(r'^add/$',idc.AddIdcView.as_view()),
        ])),
        url(r'^get_sever_info_api/$',server.get_sever_info_api.as_view()),
        url(r'^list/$',server.get_server_list_view.as_view()),
        url(r'^modifystatus/$',server.ModifyStatusView.as_view()),
        url(r'^modifyproduct/$',server.ModifyProductView.as_view()),
        url(r'^productoptions/$',server.ProductOptions.as_view()),
        url(r'^product/',include([
            url(r'^list/$',product.ListProductView.as_view()),
            url(r'^add/$',product.AddProductView.as_view() ,name='product_add'),
            url(r'^list_node_info/$',product.ListNodeInfoView.as_view()),
            url(r'^modify/$',product.ModifiyView.as_view()),
            url(r'^hostlist/$',product.HostListView.as_view()),
        ])),

    ]
    )),
    url(r'^monitor/', include([
        url(r'^zabbix/',include([
            url(r'^hostrsync/$',zabbix.HostRsyncView.as_view()),
            url(r'^linktemplate/$',template.LinktemplateView.as_view()),
            url(r'^hoststatus/$',template.GetHostStatusView.as_view()),


        ])),

    ]
    )),


]

reboot_lianxi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('dashborad.urls')),

]

dashborad/models.py
#-*-coding:utf8-*-
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=32)
    code = models.CharField(max_length=32)
    class Meta:
        db_table = 'department'
        permissions = (
            ("view_userlist", "can view userlist"),
            ("view_grouplist", "can view grouplist"),
            ("view_groupuser", "can view group user"),
            ("add_groupuser", "can add group user"),
            ("del_groupuser", "can del group user"),
            ("view_usergroup", "can view user group"),
            ("add_usergroup", "can add user group"),
            ("change_groupermission", "can change group permission"),




        )


class Userprofile(models.Model):
    user = models.OneToOneField(User)
    department = models.ForeignKey('Department')
    phone = models.CharField(max_length=11, null=True)
    title = models.CharField(max_length=32, null=True)
    name = models.CharField(u'中文名',max_length=32, null=True)
    email = models.EmailField(max_length=32)
    class Meta:
        db_table = 'userprofile'
        default_related_name = 'userprofile'


class UserGroup(models.Model):
    name = models.CharField(max_length=32)
    user = models.ManyToManyField('Userprofile')




class Idc(models.Model):
    name = models.CharField("idc 字母简称",max_length=10,unique=True)
    idc_name = models.CharField("idc 中文名",max_length=100)
    idc_address = models.CharField("机房的具体地址",max_length=255)
    idc_user = models.ForeignKey('Userprofile')

    class Meta:
        db_table = 'idc'
        permissions = (
            ("view_idc", "can view idc"),
        )

class Product(models.Model):
    name = models.CharField("业务线名称",max_length=32)
    p_product = models.ForeignKey("self",null=True,verbose_name="上级业务线")
    module_letter = models.CharField("字母简称",max_length=10)
    op_interface = models.CharField("运维负责人: username1,username2",max_length=255)
    dev_interface = models.CharField("业务负责人: username1,username2", max_length=255)

    def __str__(self):
        return "{}".format(self.module_letter)

    class Meta:
        db_table = "product"
        permissions = (
            ("view_product", "访问业务线"),
        )

class Server(models.Model):
    supplier        = models.IntegerField(null=True)
    manufacturers   = models.CharField(max_length=50, null=True)
    manufacture_date= models.DateField(null=True)
    server_type     = models.CharField(max_length=20, null=True)
    sn              = models.CharField(max_length=60, db_index=True, null=True)
    idc             = models.ForeignKey(Idc, null=True)
    os              = models.CharField(max_length=50, null=True)
    hostname        = models.CharField(max_length=50, db_index=True, null=True)
    inner_ip        = models.CharField(max_length=32, null=True, unique=True)
    mac_address     = models.CharField(max_length=50, null=True)
    ip_info         = models.CharField(max_length=255, null=True)
    server_cpu      = models.CharField(max_length=250, null=True)
    server_disk     = models.CharField(max_length=100, null=True)
    server_mem      = models.CharField(max_length=100, null=True)
    status          = models.CharField(max_length=100,db_index=True, null=True)
    remark          = models.TextField(null=True)
    #service_id      = models.IntegerField(db_index=True, null=True)
    server_business  = models.ForeignKey(Product,null=True,related_name='server_business')
    server_product = models.ForeignKey(Product, null=True,related_name='server_product')
    create_time     = models.DateTimeField(null=True,auto_now_add=True)
    check_update_time = models.DateTimeField(null=True,auto_now=True)
    vm_status       = models.IntegerField(db_index=True, null=True)
    uuid            = models.CharField(max_length=100, db_index=True,null=True)


    def __str__(self):
        return "{} {}".format(self.hostname, self.inner_ip)

    class Meta:
        db_table = "server"
        permissions = (
            ("view_server", "访问服务器信息"),
        )

class Status(models.Model):
    name = models.CharField(max_length=32)


class ZabbixHost(models.Model):
    server = models.OneToOneField(Server,null=True)
    zabbix_hostid = models.IntegerField(db_index=True,null=True,verbose_name='zabbix_hostid')
    zabbix_hostname = models.CharField(max_length=32,db_index=True,null=True,verbose_name='zabbix_hostname')
    zabbix_ip = models.CharField(max_length=32,db_index=True,null=True,verbose_name='zabbix_ip')
    updatetime = models.DateField(auto_now=True)

    def __str__(self):
        return  "{}.{}".format(self.zabbix_hostid,self.zabbix_hostname)

    class Meta:
        db_table = "resource_zabbix_cache"

templates/user/department.html
{% extends "public/layout.html" %}
{% block body %}
<form class="form-horizontal" method="post">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-5">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email" value="{{ user_obj.email }}" disabled>
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">部门</label>
    <div class="col-sm-5">
      <select class="form-control" name="department">
          <option value="0">请选择部门</option>
          {% for department in department_obj %}
              <option value="{{ department.id }}" {% if department.id == user_obj.userprofile.department.id %}selected{% endif %}>{{ department.name }}</option>
          {% endfor %}
        </select>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="hidden" name="id" value="{{ user_obj.id }}">
        <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>



{% endblock %}
{% block js %}
    <script>
      console.log('ssss')
     </script>
{% endblock %}

templates/user/groupermission.html
{% extends "public/layout.html" %}

{% block css %}
    <style>
        .permission-content{width: 260px !important;}
        .permission-point{margin-left: 280px !important;}
    </style>
{% endblock %}

{% block body %}
    <dl class="dl-horizontal">
        <form action="" method="post" role="form" class="form-horizontal">
        {% for ct in content_type %}
            <dt class="permission-content">{{ ct.app_label }}--{{ ct.model }}：</dt>
            <dd class="permission-point">
                <ul class="list-unstyled">
                    {% for p in ct.permission_set.all %}
                        <li>
                            <input type="checkbox" name="permission" value="{{ p.id }}" {% if p.id in group_permissions %}checked{% endif %}>
                            <label>{{ p.name }}</label>
                        </li>
                    {% endfor %}
                </ul>
            </dd>
        {% endfor %}
            <div class="form-group form-footer">
                <div class="col-sm-offset-3 col-sm-8">
                    <input type="hidden" name="group" value="{{ group }}">
                    <input type="submit" class="btn btn-primary" value="修改">
                    <input type="reset" class="btn btn-warning" value="修改">
                </div>
            </div>
        </form>
    </dl>
{% endblock %}

templates/user/grouplist.html
{% extends "public/layout.html" %}

{% block body %}
    <caption>
    <button id="add_group" class="btn btn-primary" type="button">添加用户组</button>
    </caption>
    <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>用户组名</th>
            <th>操作</th>

        </tr>
        {% for group in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ group.name }}</td>
            <td>
                <button class="btn btn-primary btn-sm show_group_users" data='{"gid": "{{ group.id }}", "groupname": "{{ group.name }}"}'>成员列表</button>
                <a class="btn btn-danger btn-sm show_group_users" href="/group/permission/?gid={{ group.id }}" >修改权限</a>
                <button class="btn btn-primary btn-sm show_group_permission" data='{{ group.id }}' >查看权限</button>

            </td>

        </tr>
        {% endfor %}
    </table>
    <div class="panel-default">
        <center>
		<ul class="pagination">
			    <li><a href="/group/list/?page=1">首页</a></li>
                {% if page_obj.has_previous == True %}
                    <li><a href="/group/list/?page={{ page_obj.previous_page_number }}">上一页</a></li>
                {%  else %}

                    <li class="previous disabled"><a>上一页</a></li>
                {% endif %}


                {% for p in page_range %}
                {#% for p in page_obj.paginator.page_range %#}
                    {%  if p == page_obj.number %}
				        <li class="active"><a href="/group/list/?page={{ p }}">{{ p }}</a></li>
                    {% else %}
                        <li><a href="/group/list/?page={{ p }}">{{ p }}</a></li>
                    {% endif %}

                {% endfor %}
                {% if page_obj.has_next == True %}
                    <li><a href="/group/list/?page={{ page_obj.next_page_number }}">下一页</a></li>
                {% else %}
				    <li class="previous disabled"><a>下一页</a></li>
                {% endif %}

			    <li><a href="/group/list/?page={{ page_obj.paginator.num_pages }}">末页</a></li>
		</ul>
	    </center>
    </div>
    <div class="modal fade" id="create_group" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4>添加group</h4>
                </div>
                <div class="modal-body form-inline">
                    <div class="form-group">
                        <label for="exampleInputName2">用户组：</label>
                        <input type="text" class="form-control" id="form_groupname" placeholder="请输入用户组名称" />
                    </div>
                    <button class="btn btn-primary" id="create_group_btn">提交</button>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="取消">
                </div>

            </div>
        </div>
    </div>
    <div class="modal fade" id="modal_show_group_users_list" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4>权限名: <span id="modal_show_group_users_list_title"></span></h4>
                </div>
                <div class="modal-body form-inline" id="modal_show_group_users_content_list">

                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="确定">
                </div>
            </div>
        </div>
    </div>
        <div class="modal fade" id="modal_show_group_permission_list" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4>用户组名: <span id="modal_show_group_permission_list_title"></span></h4>
                </div>
                <div class="modal-body form-inline" id="modal_show_group_permission_content_list">

                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="确定">
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block js %}
<script>
   $(function () {
      $('#add_group').click(function () {
          $('#create_group').modal('show');
          $('#create_group_btn').click(function () {
                var group_input = $('#form_groupname');
                var group_val = group_input.val();
                $('#create_group').modal('hide');
                if (group_val == ""){
                        swal("添加失败", "用户组名不能为空", 'error');
                        return false;
                    }
                $.post('/group/add/',{'group_name':group_val},function (res) {

                    if (res.status==0){
                        swal({
                             title: "添加成功",
                             text: " ",
                             type: "success"
                        });
                        setTimeout(function () {
                            window.location.reload()
                        },200)
                    }
                    else {
                        swal({
                             title: "添加失败",
                             type: "error",
                             text: res.message
                        })
                    }
          })
      })
      }

      );
       $('.show_group_users').click(function () {
          var modal_show_group_users_content_list = $('#modal_show_group_users_content_list');

          var data = $.parseJSON($(this).attr('data'));
          var group_name = data.groupname;
          var gid = data.gid ;
          $('#modal_show_group_users_list_title').text(group_name);
          $.get('/group/groupuserlist',{'gid':gid},function (res) {
              if (res.status == 0) {
                  var data = JSON.parse(res.data);
                  //console.log(data);
                  html = '<table class="table table-striped">';
                  html += '<tr><th>用户名</th><th>email</th><th>删除</th></tr>';
                  $.each(data, function (ke, va) {
                      html += '<tr>';
                      html += '<td>' + va.fields.username + '</td><td>' + va.fields.email + '</td>';
                      html += '<td><button class="btn btn-danger btn-xs del_group_user" data="' + va.pk + '">删除</button></td>';
                      html += '</tr>'
                  });
                  html += "</table>";
                  modal_show_group_users_content_list.empty();
                  modal_show_group_users_content_list.append(html);
                  $('#modal_show_group_users_list').modal('show');
                  $('.del_group_user').click(function () {
                      var uid = $(this).attr('data');
                      var click_obj = $(this);
                      $.ajax({
                            url:"/group/groupuserdel/",
                            type: "DELETE",
                            data: {"groupid": gid, "userid": uid},
                            datatype: "json",
                            success: function(res){
                                if (res.status == 0){
                                    click_obj.parents("tr").remove();
                                    swal("操作成功", "", "success")
                                }else{
                                    swal("操作失败", res.message, "error")
                                }
                            }
                        })
                  })
              }
              else{
                  swal({
                             title: "获取失败",
                             type: "error",
                             text: res.message
                        })
              }


          });

      });
       $('.show_group_permission').click(function () {
           var modal_show_group_permission_list = $('#modal_show_group_permission_list');
           var modal_show_group_permission_content_list = $('#modal_show_group_permission_content_list');

           modal_show_group_permission_list.modal('show');
           var data = $(this).attr('data');
           $.get('/group/permissionlist',{'gid':data},function (res) {
                  html = '<table class="table table-striped">';
                  html += '<tr><th>id</th><th>权限名</th></tr>';
                  $.each(res.data, function (ke, va) {
                      html += '<tr>';
                      html += '<td>' + va.id + '</td><td>' + va.name + '</td>';
                      html += '</tr>'
                  });
                  html += "</table>";
                  modal_show_group_permission_content_list.empty();
                  modal_show_group_permission_content_list.append(html);

           })
       })

   })
</script>
{% endblock %}

templates/user/login.html
<!DOCTYPE html>
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="robots" content="index,follow">
    <meta name="Author" content="reboot">

    <link href="/static/img/favicon.ico" type="image/x-icon" rel="shortcut icon">
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/alert/sweet-alert.css" rel="stylesheet">
    <style type="text/css">
        body {
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: #eee;
        }
        .form-signin {
          max-width: 330px;
          padding: 15px;
          margin: 0 auto;
        }
        </style>
 
    <title>Devops平台 - 管理员登陆</title>
    </head>
    <body>
        <!--loginbox again-->
    <div class="container">
            <form class="form-signin" id="loginform">
                <h2 class="form-signin-heading" style="text-align: center;">用户登录</h2>
                <div class="form-group">
                  <input type="text" id="username" class="form-control" name="username" value="{{ request.COOKIES.username }}" placeholder="用户名"/>
                </div>
                <div class="form-group">
                    <input type="password" id="password" class="form-control" value="{{ request.COOKIES.password }}" name="password" placeholder="密码"/>
                </div>
                <button type="submit" class="btn btn-lg btn-primary btn-block">登录</button>
                <a id='forget'>忘记密码</a> <input class="remember" type="checkbox"> 记住密码
            </form>
      </div>

	

        <script type="text/javascript" src="/static/vendor/alert/sweet-alert.min.js"></script>
        <script src="/static/vendor/jquery/jquery.min.js"></script>
        <script src="/static/vendor/jquery/jquery.cookie.js"></script>

<script type="text/javascript">
/* 忘记密码提示*/
$("#forget").click(function() {
    str="请联系管理员帮您重置密码"+'\n'+"邮箱：xiaoyong.feng@reboot.com"
    swal(str)
});

$(function() {
  $('.remember').click(function () {
      var username = $('#username').val();
      var password = $('#password').val();
      $.cookie('username',username,{expires:7,path:'/'});
      $.cookie('password',password,{expires:7,path:'/'});
  })    
});


/*用户登录*/
$('#loginform').on('submit',function(){
    var str = $('#loginform').serialize()
    $.post('#',str,function(res){
        console.log(res)
        if (res.status == 0){
            //alert("登陆成功")
            location.href=res.next_url
        }else{
            swal({
                title: res.errmsg,
                type: "error",
                confirmButtonText: "知道了"
            },function(){
                $("#username").val("")
                $("#password").val("")
            }); 

        }
    });
    return false;

})








</script>


</body></html>

templates/user/userlistl.html
{% extends "public/layout.html" %}

{% block body %}
    <form class="form-inline">
        <div class="form-group">
            <label class="sr-only" for="exampleInputPassword3">Password</label>
            <input type="text" class="form-control" name="name" id="exampleInputPassword3" value="{{ name }}" placeholder="请输入name值">
        </div>

        <button type="submit" class="btn btn-primary">搜索</button>
    </form>
    <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>用户名</th>
            <th>中文名</th>
            <th>email</th>
            <th>电话</th>
            <th>部门</th>
            <th>用户组</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        {% for user in object_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.userprofile.name|default_if_none:''}}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.userprofile.phone }}</td>
            <td>{{ user.userprofile.department.name}}</td>
            <td> {% for group in user.groups.all %}
                 {{ group.name }}
                 {% endfor %}
            </td>
            <td class="user_status">
                {% if user.is_active %}
                    <span class="glyphicon glyphicon-ok-circle text-success"></span>正常
                {% else %}
                    <span class="glyphicon glyphicon-warning-sign text-warning"></span>禁止
                {% endif %}
            </td>
            <td>
                <div class="btn-group">
                    <div class="btn-group">
                        <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="false">
                            修改
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            {% if perms.dashboard.change_department %}
                             <li role="presentation"><a role="menuitem" tabindex="-1" href="/user/modifydepartment/?user={{ user.id }}">部门</a></li>
                            {% endif %}
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="/user/modifyphone/?user={{ user.id }}">phone</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#" data='{"uid":"{{ user.id }}","email":"{{ user.email }}"}' class="user_to_group">用户组</a></li>
                        </ul>
                    </div>
                    {% if user.is_active %}
                        <button type="button" class="btn btn-sm btn-warning modify_user_status" status="true" data="{{ user.id }}">禁用</button>
                    {% else %}
                        <button type="button" class="btn btn-sm modify_user_status btn-info" status="false" data="{{ user.id }}">开启</button>
                    {% endif %}
                </div>
            </td>
        </tr>
        {% endfor %}
    </table>
    <div class="panel-default">
        <center>
		<ul class="pagination">
			<li><a href="/user/list/?page=1">首页</a></li>
                {% if page_obj.has_previous == True %}
                    <li><a href="/user/userlist/?page={{ page_obj.previous_page_number }}">上一页</a></li>
                {%  else %}

                    <li class="previous disabled"><a>上一页</a></li>
                {% endif %}


                {% for p in page_range %}
                {#% for p in page_obj.paginator.page_range %#}
                    {%  if p == page_obj.number %}
				        <li class="active"><a href="/user/userlist/?page={{ p }}">{{ p }}</a></li>
                    {% else %}
                        <li><a href="/user/userlist/?page={{ p }}">{{ p }}</a></li>
                    {% endif %}

                {% endfor %}
                {% if page_obj.has_next == True %}
                    <li><a href="/user/userlist/?page={{ page_obj.next_page_number }}">下一页</a></li>
                {% else %}
				    <li class="previous disabled"><a>下一页</a></li>
                {% endif %}

			<li><a href="/user/list/?page={{ page_obj.paginator.count }}">末页</a></li>
		</ul>
	    </center>
    </div>

    <div class="modal fade" id="user_to_group_modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 id="user_to_group_modal_title"></h4>
                </div>
                <div class="modal-body form-inline col-xs-6">
                    <select class="form-control" id="all_user_group">
                    </select>
                    <button class="btn btn-primary" id="user_to_group_btn">提交</button>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-default" data-dismiss="modal" aria-hidden="true" type="button" value="取消">
                </div>

            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
<script>

    function change_user_status(status_td_obj, status){
        if (status == "true"){
            status_td_obj.html('<span class="glyphicon glyphicon-warning-sign text-warning"></span>禁止')
        }else{
            status_td_obj.html('<span class="glyphicon glyphicon-ok-circle text-success"></span>正常')
        }
    }
    function modify_user_status(user_id){
        $.post("/user/modifystatus/", {"user_id": user_id}, function(res){
            if (res.status != 0){
                swal({
                    title: res.errmsg,
                    type: "error",
                    confirmButtonText: "知道了"
                });
            }
            else {
                change_user_status(click_obj.parents("td").siblings(".user_status"), status);
            }
        })
    }
    $(function(){
        $(".modify_user_status").click(function(){
            var click_obj = $(this);
            var status = click_obj.attr("status");
            if(status === "true"){
                click_obj.removeClass("btn-warning").addClass("btn-info").attr("status", "false").text("开启");
            }else{
                click_obj.removeClass("btn-info").addClass("btn-warning").attr("status", "true").text("禁用");

            }
            modify_user_status(click_obj.attr('data'));


        });

        $(".user_to_group").click(function () {

            var user_to_group_data = $.parseJSON($(this).attr('data'));
            var email = user_to_group_data.email;
            var user_id = user_to_group_data.uid;
            var all_user_group = $("#all_user_group");
            all_user_group.empty();
            $('#user_to_group_modal_title').text(email+'添加用户组');
            $.get('/group/usergrouplist/',{"uid":user_id},function (res) {
                if (res.status==0){
                    var data = $.parseJSON(res.data);
                    var html = '<option value="0">请选择用户组</option>';
                    $.each(data,function (ke,va) {

                        html += '<option value ='+va.pk+'>'+va.fields.name+'</option>';
                    });
                    all_user_group.append(html);
                    $('#user_to_group_modal').modal('show');
                }
                else {
                     swal({
                             title: "获取用户组失败",
                             type: "error",
                             text: res.message
                        })
                }


            });
            $('#user_to_group_btn').click(function () {
                var group_id = $('#all_user_group').val();
                $('#user_to_group_modal').modal('hide');
                $.post('/group/usergroupadd/',{"group_id":group_id,"user_id":user_id},function (res) {
                    if (res.status ==0){
                        swal({
                             title: "添加成功",
                             type: "success",
                             text: ''
                        });
                        setTimeout(function () {
                            window.location.reload()
                        },500)
                    }
                    else {
                        swal({
                             title: "添加失败",
                             type: "error",
                             text: res.message
                        })
                    }
                })
            })
        });
    })
</script>
{% endblock %}